services:
  server:
    build:
      context: ..
      dockerfile: ./build/server.dockerfile
    ports:
      - 8081:8080

  client:
    build:
      context: ..
      dockerfile: ./build/client.dockerfile
    ports:
      - 8085:8080
